/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_FEBB7173__
#define __PLUGINEDITOR_H_FEBB7173__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SpectralDelayPluginAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    SpectralDelayPluginAudioProcessorEditor (SpectralDelayPluginAudioProcessor* ownerFilter);
    ~SpectralDelayPluginAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_FEBB7173__
